version: "3"

services:
  db:
    build:
      context: ./db
    ports:
      - 3306:3306
    volumes:
      - ./db/var/lib/mysql:/var/lib/mysql
    environment:
      - MYSQL_DATABASE=laravel
      - MYSQL_USER=laravel
      - MYSQL_PASSWORD=password
      - MYSQL_ROOT_PASSWORD=password
    platform: linux/x86_64
    # PHPMyAdminサーバー
  phpmyadmin: # デフォルトのままで不都合ないのでDockerHubにあるイメージをそのまま使う
    image: phpmyadmin/phpmyadmin:latest
    platform: 'linux/amd64'  # m1 Macの記述?
    environment:
      DB_HOST: db # ホストはデータベースサーバーのサービス名(26行目)
      DB_USERNAME: root # デフォルトでログインしているユーザー(今回はルートユーザー)
      DB_PASSWORD: password # 上記ユーザーのパスワード(今回はルートユーザーのパスワード)
    ports: # ポートの設定(後で.envでする)
    - 8081:80
  app:
    build:
      context: ./app
    volumes:
      - ../src:/work/backend
    depends_on: ["db"]
  web:
    build:
      context: ./web
    ports:
      - 80:80
    volumes:
      - ../src:/work/backend
    depends_on: ["app"]

  mail:
    image: mailhog/mailhog
    container_name: mailhog
    ports:
      - "8025:8025"
    environment:
      MH_STORAGE: maildir
      MH_MAILDIR_PATH: /tmp